WANDB:
  ENABLED: False
MODEL:
  DEVICE: "cuda"
  MASK_ON: True
  META_ARCHITECTURE: "SepInst"
  USE_DEPTH: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_THRESHOLD: 0.5
  DATASET_MAPPER: "RGBDDatasetMapper"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 2
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    FPN_STRIDES: [4, 8, 16, 32, 64]
    YIELD_PROPOSAL: False
    YIELD_BOX_FEATURES: False
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
    NUM_SHARE_CONVS: 0
    USE_DEFORMABLE: False
    NORM: "GN"
    USE_SCALE: True
    PRIOR_PROB: 0.01
    INFERENCE_TH_TRAIN: 0.05
    PRE_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TRAIN: 100
    INFERENCE_TH_TEST: 0.05
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 100
    NMS_TH: 0.6
    THRESH_WITH_CTR: False
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    BOX_QUALITY: "ctrness"
    SIZES_OF_INTEREST: [64, 128, 256, 512]
    LOSS_NORMALIZER_CLS: "fg"
    LOSS_WEIGHT_CLS: 1.0
  FUSION:
    NAME: "MultAddFusion"
    NORM: "BN"
    IN_CHANNELS: 256
  ROI_MASK_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
  LOSS:
    DOUBLE_LOSS: True
    DICE_LOSS: False
    LOC_WEIGHT: 1.0
    CENTERNESS_WEIGHT: 1.0
    CLASS_WEIGHT: 1.0
    MASK_RGB_WEIGHT: 1.3
    MASK_RGBD_WEIGHT: 1.3
    DICE_RGB_WEIGHT : 1.5
    DICE_RGBD_WEIGHT : 1.5
  MATCHER:
    NAME: "IoUMatcher"
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00005
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 10000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0
  AMSGRAD: False
TEST:
  EVAL_PERIOD: 10000

VERSION: 2